apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: testserver
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicaSet
    name: testserver